module.exports = {
  "code": 0,
  "message": "成功请求",
  "data": [{
    "lanmu_id": 0,
    "lanmu_name": "校精选",
    "lanmu_order": 0,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=0"
  }, {
    "lanmu_id": 32,
    "lanmu_name": "悦青春",
    "lanmu_order": 1,
    "lanmu_menu": 1,
    "lanmu_custom": 1,
    "lanmu_json": "/V2/news/list.html?chid=32"
  }, {
    "lanmu_id": 59,
    "lanmu_name": "闯未来",
    "lanmu_order": 2,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=59"
  }, {
    "lanmu_id": 61,
    "lanmu_name": "看世界",
    "lanmu_order": 3,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=61"
  }, {
    "lanmu_id": 13,
    "lanmu_name": "秀自我",
    "lanmu_order": 4,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=13"
  }, {
    "lanmu_id": 30,
    "lanmu_name": "知天下",
    "lanmu_order": 5,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=30"
  }],
  "updateDime": 1471398874
}